name: Stop Docker Containers on EC2

on:
  workflow_dispatch:   # manual trigger from GitHub

jobs:
  stop-containers:
    runs-on: ubuntu-latest

    steps:
      - name: SSH & Stop Docker Compose
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}      
          username: ${{ secrets.EC2_USER }}  
          key: ${{ secrets.EC2_KEY }}        
          port: 22
          script: |
            cd /home/ubuntu/emartapp
            docker-compose down
